-- ============================================================
-- 04_seed.sql — initial catalog data.
-- Run AFTER 01_schema.sql, 02_rls.sql, 03_storage.sql.
--
-- Localized JSONB fields (title/name/description) carry the same text in
-- tr/en/ar where the original data had only one language. Translate and add
-- images via the /admin panel afterward.
-- ============================================================

begin;

-- Categories
insert into public.categories (id, slug, name, image_url, show_in_navbar, is_mega_menu, mega_menu_content) values ('ce063502-d88c-425d-9816-321ba76bb7ed', 'coat', '{"tr":"coat","en":"coat","ar":"coat"}'::jsonb, null, false, false, null);
insert into public.categories (id, slug, name, image_url, show_in_navbar, is_mega_menu, mega_menu_content) values ('0bc7ce39-8b32-4ee3-96fe-2153c4f9ee4a', 'banana', '{"tr":"banana","en":"banana","ar":"banana"}'::jsonb, null, true, false, null);
insert into public.categories (id, slug, name, image_url, show_in_navbar, is_mega_menu, mega_menu_content) values ('989b4ba7-4de7-4d4a-a4a4-325b665b773c', 'slug', '{"tr":"havuc","en":"havuc","ar":"havuc"}'::jsonb, null, true, false, null);
insert into public.categories (id, slug, name, image_url, show_in_navbar, is_mega_menu, mega_menu_content) values ('b85a3299-f055-4c3e-8268-d79bd80caa70', 'watches', '{"tr":"watches","en":"watches","ar":"watches"}'::jsonb, null, true, false, '[{"title":"Tops & Shirts","links":[{"title":"T-Shirts","href":"/products?category=t-shirt"},{"title":"Sweatshirts","href":"/products?category=sweat"},{"title":"Coats & Jackets","href":"/products?category=coat"}]},{"title":"Bottoms","links":[{"title":"Trousers & Pants","href":"/products?category=trousers"},{"title":"Shorts","href":"/products?category=shorts"},{"title":"Shoes","href":"/products?category=shoe"}]},{"title":"Special Offers","links":[{"title":"New Arrivals","href":"/products?sort=new"},{"title":"Discounted Items","href":"/discount"}]}]'::jsonb);
insert into public.categories (id, slug, name, image_url, show_in_navbar, is_mega_menu, mega_menu_content) values ('988e08a5-d511-411a-9563-c607ff0bc074', 'title', '{"tr":"title","en":"title","ar":"title"}'::jsonb, null, true, false, null);
insert into public.categories (id, slug, name, image_url, show_in_navbar, is_mega_menu, mega_menu_content) values ('5df8a94f-df5c-46ab-aee3-dc697646c4f9', 'banana-37', '{"tr":"banana","en":"banana","ar":"banana"}'::jsonb, null, true, false, null);

-- Products
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('e9529ef3-6ab5-48f1-ab9a-d122dacccd8a', 'it-goes', '{"tr":"it goes","en":"it goes","ar":"it goes"}'::jsonb, '{"tr":"","en":"","ar":""}'::jsonb, 1350.00, true, '22', '250', '10', true, false, true, false, true, false, '0bc7ce39-8b32-4ee3-96fe-2153c4f9ee4a', '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('2e2a9d95-e4d7-45e2-af2c-e89b121d46d2', 'rush', '{"tr":"rush","en":"rush","ar":"rush"}'::jsonb, '{"tr":"","en":"","ar":""}'::jsonb, 40000000.00, true, null, null, null, false, false, false, false, false, false, 'b85a3299-f055-4c3e-8268-d79bd80caa70', '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('179fd59b-8777-4a1f-8cf7-c9409a4126a0', 'me-for', '{"tr":"me for","en":"me for","ar":"me for"}'::jsonb, '{"tr":"","en":"","ar":""}'::jsonb, 150.00, true, null, null, null, false, false, false, false, false, false, 'b85a3299-f055-4c3e-8268-d79bd80caa70', '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('0a7ad87c-539d-41af-b8b3-9bf3a06fe78b', 'hahahaha-smells-grape-haha', '{"tr":"hahahaha smells grape haha","en":"hahahaha smells grape haha","ar":"hahahaha smells grape haha"}'::jsonb, '{"tr":"","en":"","ar":""}'::jsonb, 704.00, true, null, null, null, true, false, true, true, false, false, '989b4ba7-4de7-4d4a-a4a4-325b665b773c', '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('ddb3cc39-b36f-4981-9267-8dd96ccc677f', 'majoodidoodi', '{"tr":"majoodidoodi ","en":"majoodidoodi ","ar":"majoodidoodi "}'::jsonb, '{"tr":"","en":"","ar":""}'::jsonb, 99999999.99, true, null, null, null, false, false, false, false, false, false, '989b4ba7-4de7-4d4a-a4a4-325b665b773c', '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('926e1871-b5d7-427e-8fff-dd09772729a8', 'mamdali', '{"tr":"mamdali","en":"mamdali","ar":"mamdali"}'::jsonb, '{"tr":"","en":"","ar":""}'::jsonb, 50.00, true, null, null, null, false, false, false, false, false, false, '0bc7ce39-8b32-4ee3-96fe-2153c4f9ee4a', '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('3d93ee04-ffc0-4957-a6e7-adaabc368b4c', 'banana', '{"tr":"banana","en":"banana","ar":"banana"}'::jsonb, '{"tr":"banana orange","en":"banana orange","ar":"banana orange"}'::jsonb, 150.00, false, '22', '1000', 'xs', false, false, false, false, false, false, null, '{}'::text[]);
insert into public.products (id, slug, title, description, price, is_featured, model_height, model_weight, model_size, size_xs, size_s, size_m, size_l, size_xl, size_xxl, category_id, images) values ('85a0055b-d943-4990-afc1-37df590cf741', 'banana-1', '{"tr":"banana","en":"banana","ar":"banana"}'::jsonb, '{"tr":"sadsdsfd","en":"sadsdsfd","ar":"sadsdsfd"}'::jsonb, 1234.00, true, null, null, null, false, false, false, false, false, false, '0bc7ce39-8b32-4ee3-96fe-2153c4f9ee4a', '{}'::text[]);

commit;
