import { cartProduct } from "./types";

export const CARTPRODUCTS: cartProduct[] = [
    {
        id: 1,
        title: "Products.productCardTitle.1",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "S",
    },
    {
        id: 2,
        title: "Products.productCardTitle.2",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "M",
    },
    {
        id: 3,
        title: "Products.productCardTitle.3",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "L",
    },
    {
        id: 4,
        title: "Products.productCardTitle.4",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "XL",
    },
    {
        id: 5,
        title: "Products.productCardTitle.5",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "XXL",
    },
    {
        id: 6,
        title: "Products.productCardTitle.6",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "XXXL",
    },
    {
        id: 7,
        title: "Products.productCardTitle.7",
        originalPrice: "₺1.599,99",
        currentPrice: "₺1.399,99",
        imageUrl: "/image1.jpeg",
        size: "XXXXL",
    },
];
