import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Footer } from "@/src/components/footer/footer";
// 1. Import the provider and the server-side message fetcher
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// 2. Make the RootLayout async
export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// 3. Fetch the translation messages on the server
	const messages = await getMessages();

	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				{/* 4. Wrap the app contents in the provider and pass the messages */}
				<NextIntlClientProvider messages={messages}>
					{children}
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}